import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
README = ROOT / "README.md"
DOCS = ROOT / "docs"
WEBSITE = ROOT / "website"


def _plain_language_section(text: str) -> str:
    start = text.index("# What this project is trying to achieve, in plain language")
    end = text.index("# Abstract", start)
    return text[start:end]


def test_p78_core_artifacts_exist() -> None:
    required = (
        DOCS / "proposition_78_certified_continuous_model_separation.md",
        DOCS / "p78_equation_provenance.md",
        DOCS / "figures" / "p78_certified_continuous_model_separation.svg",
        ROOT / "src" / "consciousness_bridge" / "certified_continuous_model_separation.py",
        ROOT / "tests" / "test_certified_continuous_model_separation.py",
        ROOT / "tests" / "test_p78_figure_geometry.py",
    )
    for path in required:
        assert path.exists(), path


def test_p78_is_exposed_across_public_research_surfaces() -> None:
    readme = README.read_text(encoding="utf-8")
    roadmap = (DOCS / "theorem_roadmap.md").read_text(encoding="utf-8")
    navigation = (DOCS / "research_navigation.md").read_text(encoding="utf-8")
    detail = (DOCS / "detailed_proposition_record.md").read_text(encoding="utf-8")
    equation_map = (DOCS / "equation_and_citation_map.md").read_text(encoding="utf-8")
    website = (WEBSITE / "index.html").read_text(encoding="utf-8")
    research_map = (WEBSITE / "research-map.html").read_text(encoding="utf-8")
    atlas = (WEBSITE / "visual-atlas.html").read_text(encoding="utf-8")

    assert "## 1.12 P78: certified continuous separation for the P75 model family" in readme
    assert "proposition_78_certified_continuous_model_separation.md" in readme
    assert "p78_equation_provenance.md" in readme
    assert "p78_certified_continuous_model_separation.svg" in readme

    assert "### P78: certified continuous separation for the P75 model family" in roadmap
    assert "proposition_78_certified_continuous_model_separation.md" in roadmap
    assert "| P78 |" in navigation
    assert "P78 certified continuous P75 model separation" in navigation
    assert "**P78** supplies the continuous-family optimization certificate required by P77" in detail
    assert "# P78 certified continuous model separation" in equation_map
    assert "p78_certified_continuous_model_separation.svg" in website
    assert "P78: Certified continuous P75 model separation" in research_map
    assert "p78_certified_continuous_model_separation.svg" in atlas


def test_p78_plain_language_explains_certificate_without_equations() -> None:
    readme = README.read_text(encoding="utf-8")
    plain = _plain_language_section(readme)

    required = (
        "P78 addresses the computational problem that P77 deliberately leaves open",
        "continuous family generated by nine parameters",
        "mathematically guaranteed lower bound for every box",
        "genuine lower bound on the distance to the whole continuous model family",
        "any explicit candidate model supplies an upper bound",
        "exact rational arithmetic",
        "separately valid upper bound on the P77 sampling radius",
        "does not turn failure to reject into model validation",
        "physical-to-experiential bridge itself remains open",
    )
    for token in required:
        assert token in plain, token

    for forbidden in ("$$", "\\boxed", "\\mathcal", "\\widehat", "\\theta"):
        assert forbidden not in plain, forbidden


def test_p78_release_metadata_and_counts_are_consistent() -> None:
    readme = README.read_text(encoding="utf-8")
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    cff = (ROOT / "CITATION.cff").read_text(encoding="utf-8")
    bib = (ROOT / "CITATION.bib").read_text(encoding="utf-8")
    citation = (ROOT / "CITATION.md").read_text(encoding="utf-8")
    changelog = (ROOT / "CHANGELOG.md").read_text(encoding="utf-8")

    assert 'version = "0.78.0"' in pyproject
    assert "version: 0.78.0" in cff
    assert "Current documented theorem frontier: P78" in cff
    assert "version      = {0.78.0}" in bib
    assert "Proposition 78" in citation
    assert "# 0.78.0 - 2026-09-10" in changelog
    assert "78 proposition-level results" in readme
    assert "66 equation-driven quantitative figures" in readme
    assert "The theorem frontier is P78." in readme

    match = re.search(r"P1 through P(\d+) with explicit dependency branches", readme)
    assert match is not None
    assert int(match.group(1)) == 78


def test_p78_certification_boundary_is_preserved() -> None:
    readme = README.read_text(encoding="utf-8")
    proof = (DOCS / "proposition_78_certified_continuous_model_separation.md").read_text(
        encoding="utf-8"
    )
    source = (
        ROOT / "src" / "consciousness_bridge" / "certified_continuous_model_separation.py"
    ).read_text(encoding="utf-8")

    source_required = (
        "local numerical best fit is an upper bound",
        "exact ``Fraction`` arithmetic",
        "does not identify the latent state with consciousness",
        "does not solve the physical-to-experiential bridge",
        "Passing an ordinary floating approximation",
    )
    for token in source_required:
        assert token in source, token

    proof_required = (
        "A candidate model gives the **upper** side of the bracket",
        "a mathematically valid upper bound on the P77 simultaneous sampling radius",
        "Converting an ordinary floating approximation",
        "a failure to reject validates the P75 model",
        "The physical-to-experiential bridge remains open.",
    )
    for token in proof_required:
        assert token in proof, token

    assert "P78 establishes a computational certification theorem" in proof
    assert "It does **not** establish that:" in proof
    assert "any explicit candidate model supplies an upper bound" in readme
    assert "separately valid upper bound on the P77 sampling radius" in readme


def test_p78_figure_sequence_is_unique_around_frontier() -> None:
    readme = README.read_text(encoding="utf-8")
    assert "**Figure 12. P77 full-law model-set separation.**" in readme
    assert "**Figure 13. P78 certified continuous model separation.**" in readme
    figure_numbers = [int(value) for value in re.findall(r"\*\*Figure (\d+)\.", readme)]
    assert len(figure_numbers) == len(set(figure_numbers))


def test_p78_publication_contains_only_permanent_artifacts() -> None:
    assert not (ROOT / ".github" / "workflows" / "p78-publication-patch.yml").exists()
    assert not (ROOT / "scripts" / "p78_publication_patch.py").exists()
