import re
from pathlib import Path


def test_release_versions_are_synchronized():
    readme = Path("README.md").read_text(encoding="utf-8")
    pyproject = Path("pyproject.toml").read_text(encoding="utf-8")
    citation = Path("CITATION.cff").read_text(encoding="utf-8")
    assert "version-0.62.0-2563eb" in readme
    assert re.search(r'^version = "0\.62\.0"$', pyproject, re.MULTILINE)
    assert re.search(r'^version: 0\.62\.0$', citation, re.MULTILINE)


def test_quantum_publication_paths_are_visible():
    readme = Path("README.md").read_text(encoding="utf-8")
    for token in (
        "Proposition 39",
        "p39_finite_data_quantum_nonfactorization.svg",
        "finite_data_quantum_nonfactorization.py",
        "test_finite_data_quantum_nonfactorization.py",
        "Proposition 40",
        "p40_continuous_quantum_region_regularity.svg",
        "continuous_quantum_region_regularity.py",
        "test_continuous_quantum_region_regularity.py",
        "Proposition 41",
        "p41_trace_ball_quantum_envelope.svg",
        "trace_ball_quantum_envelope.py",
        "test_trace_ball_quantum_envelope.py",
        "Proposition 42",
        "p42_quantum_regular_bridge_sample_complexity.svg",
        "quantum_regular_bridge_sample_complexity.py",
        "test_quantum_regular_bridge_sample_complexity.py",
        "Proposition 43",
        "p43_optimal_quantum_target_allocation.svg",
        "optimal_quantum_target_allocation.py",
        "test_optimal_quantum_target_allocation.py",
        "Proposition 44",
        "p44_pair_adaptive_sample_allocation.svg",
        "pair_adaptive_sample_allocation.py",
        "test_pair_adaptive_sample_allocation.py",
        "Proposition 45",
        "p45_shared_preparation_graph_allocation.svg",
        "shared_preparation_graph_allocation.py",
        "test_shared_preparation_graph_allocation.py",
        "Proposition 46",
        "p46_budget_constrained_witness_graph.svg",
        "budget_constrained_witness_graph.py",
        "test_budget_constrained_witness_graph.py",
        "Proposition 47",
        "p47_sequential_graph_refinement.svg",
        "sequential_witness_graph.py",
        "test_sequential_witness_graph.py",
        "Proposition 48",
        "p48_gap_dependent_stopping_complexity.svg",
        "gap_stopping_complexity.py",
        "test_gap_stopping_complexity.py",
        "Proposition 49",
        "p49_dyadic_stopping_overhead.svg",
        "dyadic_stopping_overhead.py",
        "test_dyadic_stopping_overhead.py",
        "Proposition 50",
        "p50_bounded_starvation_asynchronous_sampling.svg",
        "bounded_starvation_sampling.py",
        "test_bounded_starvation_sampling.py",
        "Proposition 51",
        "p51_heterogeneous_service_rate_stopping.svg",
        "heterogeneous_service_stopping.py",
        "test_heterogeneous_service_stopping.py",
        "Proposition 52",
        "p52_capacity_optimal_service_allocation.svg",
        "capacity_optimal_service_allocation.py",
        "test_capacity_optimal_service_allocation.py",
        "Proposition 53",
        "p53_residual_demand_reoptimization.svg",
        "residual_demand_reoptimization.py",
        "test_residual_demand_reoptimization.py",
        "Proposition 54",
        "p54_metric_switching_cost_residual_scheduling.svg",
        "metric_switching_residual_schedule.py",
        "test_metric_switching_residual_schedule.py",
        "Proposition 55",
        "p55_pruning_aware_switching_monotonicity.svg",
        "pruning_aware_switching_monotonicity.py",
        "test_pruning_aware_switching_monotonicity.py",
        "Proposition 56",
        "p56_moving_start_metric_reoptimization_stability.svg",
        "moving_start_metric_reoptimization.py",
        "test_moving_start_metric_reoptimization.py",
        "Proposition 57",
        "p57_switching_metric_perturbation.svg",
        "switching_metric_perturbation.py",
        "test_switching_metric_perturbation.py",
        "Proposition 58",
        "p58_finite_data_metric_uncertainty.svg",
        "finite_data_metric_uncertainty.py",
        "test_finite_data_metric_uncertainty.py",
        "Proposition 59",
        "p59_optimal_transition_calibration.svg",
        "optimal_transition_calibration.py",
        "test_optimal_transition_calibration.py",
        "Proposition 60",
        "p60_integer_transition_calibration.svg",
        "integer_transition_calibration.py",
        "test_integer_transition_calibration.py",
        "Proposition 61",
        "p61_exact_integer_transition_calibration.svg",
        "exact_integer_transition_calibration.py",
        "test_exact_integer_transition_calibration.py",
        "Proposition 62",
        "p62_heterogeneous_cost_transition_calibration.svg",
        "heterogeneous_cost_transition_calibration.py",
        "test_heterogeneous_cost_transition_calibration.py",
    ):
        assert token in readme
