from pathlib import Path


def test_core_research_documents_exist():
    root = Path(__file__).resolve().parents[1]
    required = [
        root / "README.md",
        root / "CHANGELOG.md",
        root / "docs" / "bridge_problem.md",
        root / "docs" / "physical_foundation.md",
        root / "docs" / "candidate_theory_families.md",
        root / "docs" / "visual_research_guide.md",
        root / "docs" / "figure_style_guide.md",
        root / "docs" / "physics_mathematics_consciousness_atlas.md",
        root / "docs" / "advanced_physics_visual_atlas.md",
        root / "docs" / "conscious_state_measurement_atlas.md",
        root / "docs" / "physics_equation_provenance.md",
        root / "docs" / "foundational_physics_mathematics_bibliography.md",
        root / "docs" / "proposition_1_representation_invariance.md",
        root / "docs" / "proposition_2_bridge_identifiability.md",
        root / "docs" / "proposition_3_bridge_equivalence_classes.md",
        root / "docs" / "proposition_4_discriminating_experiment_design.md",
        root / "docs" / "proposition_5_feature_sufficiency.md",
        root / "docs" / "proposition_6_canonical_bridge_signature.md",
        root / "docs" / "proposition_7_experimental_signature_recovery.md",
        root / "docs" / "proposition_8_robust_signature_recovery.md",
        root / "docs" / "proposition_9_categorical_sample_complexity.md",
        root / "docs" / "proposition_10_robust_experiment_design.md",
        root / "docs" / "proposition_11_intervention_resolved_causal_structure.md",
        root / "docs" / "proposition_12_component_insufficiency.md",
        root / "docs" / "proposition_13_pairwise_component_irredundancy.md",
        root / "docs" / "proposition_14_temporal_continuation.md",
        root / "docs" / "proposition_15_finite_sample_temporal_certification.md",
        root / "docs" / "proposition_16_independent_composition_and_coupling.md",
        root / "docs" / "proposition_17_coarse_graining_and_refinement.md",
        root / "docs" / "universal_proof_target.md",
        root / "docs" / "equation_and_citation_map.md",
        root / "docs" / "axiom_ledger.md",
        root / "docs" / "theorem_roadmap.md",
        root / "docs" / "falsification_program.md",
        root / "docs" / "research_architecture.md",
        root / "docs" / "literature_map.md",
        root / "docs" / "figures" / "research_architecture.svg",
        root / "docs" / "figures" / "theorem_roadmap.svg",
        root / "docs" / "figures" / "physics_mathematics_atlas.svg",
        root / "docs" / "figures" / "equation_evidence_map.svg",
        root / "docs" / "figures" / "thermodynamics_information_processing.svg",
        root / "docs" / "figures" / "information_geometry_response_manifold.svg",
        root / "docs" / "figures" / "conscious_state_measurement_map.svg",
        root / "docs" / "figures" / "spaceflight_extreme_environment_map.svg",
        root / "docs" / "figures" / "causal_structure_anatomy.svg",
        root / "docs" / "figures" / "p12_collision_map.svg",
        root / "docs" / "figures" / "p13_component_irredundancy.svg",
        root / "docs" / "figures" / "p14_temporal_continuation.svg",
        root / "docs" / "figures" / "p15_finite_sample_temporal_certification.svg",
        root / "docs" / "figures" / "p16_composition_coupling.svg",
        root / "docs" / "figures" / "p17_coarse_graining_refinement.svg",
        root / "docs" / "figures" / "universal_proof_ladder.svg",
        root / "docs" / "figures" / "theory_comparison_map.svg",
        root / "src" / "consciousness_bridge" / "intervention_causal_structure.py",
        root / "src" / "consciousness_bridge" / "causal_structure_minimality.py",
        root / "src" / "consciousness_bridge" / "causal_structure_pairwise_minimality.py",
        root / "src" / "consciousness_bridge" / "temporal_causal_structure.py",
        root / "src" / "consciousness_bridge" / "temporal_certification.py",
        root / "src" / "consciousness_bridge" / "causal_structure_composition.py",
        root / "src" / "consciousness_bridge" / "causal_structure_coarse_graining.py",
        root / "tests" / "test_intervention_causal_structure.py",
        root / "tests" / "test_causal_structure_minimality.py",
        root / "tests" / "test_causal_structure_pairwise_minimality.py",
        root / "tests" / "test_temporal_causal_structure.py",
        root / "tests" / "test_temporal_certification.py",
        root / "tests" / "test_causal_structure_composition.py",
        root / "tests" / "test_causal_structure_coarse_graining.py",
        root / "tests" / "test_visual_and_terminology_quality.py",
        root / "references.bib",
        root / "foundational_physics_mathematics.bib",
        root / "empirical_consciousness_measurement.bib",
        root / "CITATION.cff",
    ]
    missing = [str(path.relative_to(root)) for path in required if not path.exists()]
    assert not missing, f"Missing research documents: {missing}"
