"""P80 simplex-coupled box certificates for the P78 continuous P75 search.

P78 encloses each of the sixteen P75 observed-cell probabilities over a
parameter box and lower-bounds L-infinity model distance by the largest
coordinatewise distance to those intervals. That bound is rigorous, but it
forgets one piece of structure that every probability law must obey: the cell
probabilities sum to one.

P80 intersects the P78 coordinate intervals with the probability simplex. The
resulting interval-simplex relaxation still contains every P75 law generated by
the parameter box, so distance to that relaxation is a valid lower bound on
distance to the true box image. Because the interval-simplex relaxation is a
subset of the uncoupled coordinate box, the P80 bound always dominates the P78
coordinatewise bound and can be strictly stronger.

For an empirical law p and rational interval bounds l_i <= q_i <= u_i, the
exact L-infinity distance to the interval-simplex relaxation is the smallest
r >= 0 for which every clipped coordinate interval is nonempty and

    sum_i max(l_i, p_i-r) <= 1 <= sum_i min(u_i, p_i+r).

The nonempty-coordinate requirement is exactly the ordinary product-box
L-infinity distance used by P78. The two mass conditions are monotone
piecewise-linear functions with rational breakpoints. The implementation below
solves both crossing radii exactly and takes their maximum together with the
P78 coordinatewise radius. All certification arithmetic uses
``fractions.Fraction``; no floating optimizer is used.

This is a tighter computational relaxation of the P75 observed-law family. It
does not validate the latent target model. It does not identify a latent state
with consciousness, and it does not solve the physical-to-experiential bridge.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from fractions import Fraction
from heapq import heappop, heappush

from consciousness_bridge.certified_continuous_model_separation import (
    P78ParameterBox,
    empirical_law_from_counts,
    linf_distance_exact,
    p75_box_cell_intervals_exact,
    p75_box_linf_lower_bound_exact,
    p75_four_view_law_exact,
)
from consciousness_bridge.certified_sampling_radius import P79SamplingRadiusCertificate


@dataclass(frozen=True)
class P80DistanceBracket:
    """Certified global L-infinity bracket using simplex-coupled box bounds."""

    lower_bound: Fraction
    upper_bound: Fraction
    best_parameters: tuple[Fraction, ...]
    leaf_count: int
    evaluated_boxes: int
    iterations: int
    maximum_active_width_sum: Fraction
    p78_active_lower_bound: Fraction
    p78_mesh_upper_bound: Fraction
    certified_gap: Fraction
    root_p78_bound: Fraction
    root_p80_bound: Fraction
    root_tightening: Fraction
    conclusion: str


def _require_fraction_vector(
    values: tuple[Fraction, ...],
    *,
    name: str,
) -> None:
    if not values:
        raise ValueError(f"{name} must be nonempty")
    for index, value in enumerate(values):
        if not isinstance(value, Fraction):
            raise TypeError(f"{name}[{index}] must be a fractions.Fraction")


def _validate_interval_simplex_inputs(
    empirical_law: tuple[Fraction, ...],
    lower: tuple[Fraction, ...],
    upper: tuple[Fraction, ...],
) -> None:
    _require_fraction_vector(empirical_law, name="empirical_law")
    _require_fraction_vector(lower, name="lower")
    _require_fraction_vector(upper, name="upper")
    if not (len(empirical_law) == len(lower) == len(upper)):
        raise ValueError("empirical_law, lower, and upper must have equal length")

    for index, value in enumerate(empirical_law):
        if value < 0 or value > 1:
            raise ValueError(f"empirical_law[{index}] must lie in [0, 1]")
    if sum(empirical_law, start=Fraction(0)) != 1:
        raise ValueError("empirical_law must sum exactly to one")

    for index, (lo, hi) in enumerate(zip(lower, upper, strict=True)):
        if lo < 0 or hi > 1 or lo > hi:
            raise ValueError(
                f"interval {index} must satisfy 0 <= lower <= upper <= 1"
            )

    lower_mass = sum(lower, start=Fraction(0))
    upper_mass = sum(upper, start=Fraction(0))
    if lower_mass > 1 or upper_mass < 1:
        raise ValueError("coordinate intervals have empty intersection with the simplex")


def _first_piecewise_linear_crossing(
    *,
    breakpoints: tuple[Fraction, ...],
    value_at: Callable[[Fraction], Fraction],
    target: Fraction,
    increasing: bool,
) -> Fraction:
    """Return the first exact crossing of a continuous monotone PL function."""

    points = sorted({Fraction(0), *breakpoints})
    left = points[0]
    left_value = value_at(left)
    if (increasing and left_value >= target) or (
        not increasing and left_value <= target
    ):
        return left

    for right in points[1:]:
        right_value = value_at(right)
        crossed = right_value >= target if increasing else right_value <= target
        if crossed:
            slope = (right_value - left_value) / (right - left)
            if slope == 0:
                return right
            root = left + (target - left_value) / slope
            if root < left or root > right:
                raise RuntimeError("piecewise-linear crossing escaped its segment")
            return root
        left = right
        left_value = right_value

    final_value = value_at(points[-1])
    if (increasing and final_value >= target) or (
        not increasing and final_value <= target
    ):
        return points[-1]
    raise RuntimeError("monotone crossing was not reached")


def uncoupled_interval_linf_distance_exact(
    empirical_law: tuple[Fraction, ...],
    lower: tuple[Fraction, ...],
    upper: tuple[Fraction, ...],
) -> Fraction:
    """Return the product-box L-infinity distance used by the P78 relaxation."""

    _validate_interval_simplex_inputs(empirical_law, lower, upper)
    distances = []
    for observed, lo, hi in zip(empirical_law, lower, upper, strict=True):
        if observed < lo:
            distances.append(lo - observed)
        elif observed > hi:
            distances.append(observed - hi)
        else:
            distances.append(Fraction(0))
    return max(distances)


def interval_simplex_linf_distance_exact(
    empirical_law: tuple[Fraction, ...],
    lower: tuple[Fraction, ...],
    upper: tuple[Fraction, ...],
) -> Fraction:
    """Return exact distance from ``empirical_law`` to an interval simplex.

    The interval-simplex relaxation is

        R = {q : sum(q)=1 and lower_i <= q_i <= upper_i for every i}.

    At radius ``r`` the feasible coordinate interval is

        [max(lower_i, p_i-r), min(upper_i, p_i+r)].

    Feasibility therefore requires both coordinatewise nonemptiness and the
    interval-sum condition that one lies between the summed lower and upper
    endpoints. The coordinatewise threshold is exactly the uncoupled P78
    interval distance, so the exact coupled distance is the maximum of that
    threshold and the two monotone mass-crossing thresholds.
    """

    _validate_interval_simplex_inputs(empirical_law, lower, upper)
    coordinate_radius = uncoupled_interval_linf_distance_exact(
        empirical_law,
        lower,
        upper,
    )

    def lower_mass(radius: Fraction) -> Fraction:
        return sum(
            (
                max(lo, observed - radius)
                for observed, lo in zip(empirical_law, lower, strict=True)
            ),
            start=Fraction(0),
        )

    def upper_mass(radius: Fraction) -> Fraction:
        return sum(
            (
                min(hi, observed + radius)
                for observed, hi in zip(empirical_law, upper, strict=True)
            ),
            start=Fraction(0),
        )

    lower_breakpoints = tuple(
        observed - lo
        for observed, lo in zip(empirical_law, lower, strict=True)
        if observed > lo
    )
    upper_breakpoints = tuple(
        hi - observed
        for observed, hi in zip(empirical_law, upper, strict=True)
        if hi > observed
    )

    radius_for_lower_mass = _first_piecewise_linear_crossing(
        breakpoints=lower_breakpoints,
        value_at=lower_mass,
        target=Fraction(1),
        increasing=False,
    )
    radius_for_upper_mass = _first_piecewise_linear_crossing(
        breakpoints=upper_breakpoints,
        value_at=upper_mass,
        target=Fraction(1),
        increasing=True,
    )
    return max(
        coordinate_radius,
        radius_for_lower_mass,
        radius_for_upper_mass,
    )


def p75_box_simplex_linf_lower_bound_exact(
    empirical_law: tuple[Fraction, ...],
    box: P78ParameterBox,
) -> Fraction:
    """Return the P80 simplex-coupled lower bound for one P78 parameter box."""

    if len(empirical_law) != 16:
        raise ValueError("empirical_law must contain sixteen probabilities")
    cell_lower, cell_upper = p75_box_cell_intervals_exact(box)
    return interval_simplex_linf_distance_exact(
        empirical_law,
        cell_lower,
        cell_upper,
    )


def p80_dominates_p78_on_box(
    empirical_law: tuple[Fraction, ...],
    box: P78ParameterBox,
) -> bool:
    """Return the exact dominance check P80(B) >= P78(B)."""

    return p75_box_simplex_linf_lower_bound_exact(
        empirical_law,
        box,
    ) >= p75_box_linf_lower_bound_exact(empirical_law, box)


def certified_p75_linf_branch_and_bound_simplex(
    counts: tuple[int, ...],
    *,
    max_leaves: int = 256,
    gap_tolerance: Fraction = Fraction(0),
) -> P80DistanceBracket:
    """Return a global P75 distance bracket using P80 box lower bounds.

    Active boxes always partition the full P75 parameter cube. P80 lower
    bounds drive refinement. Explicit box centers provide valid global upper
    bounds. For an additional certified mesh upper bound, the routine retains
    the P78 coordinatewise lower bound on every active box and applies P78's
    established mesh-width certificate to that original lower-bound family.
    """

    if isinstance(max_leaves, bool) or not isinstance(max_leaves, int):
        raise TypeError("max_leaves must be an integer")
    if max_leaves < 1:
        raise ValueError("max_leaves must be positive")
    if not isinstance(gap_tolerance, Fraction):
        raise TypeError("gap_tolerance must be a fractions.Fraction")
    if gap_tolerance < 0:
        raise ValueError("gap_tolerance must be nonnegative")

    empirical_law = empirical_law_from_counts(counts)
    root = P78ParameterBox.unit_cube()
    root_p78 = p75_box_linf_lower_bound_exact(empirical_law, root)
    root_p80 = p75_box_simplex_linf_lower_bound_exact(empirical_law, root)
    root_center = root.center
    root_upper = linf_distance_exact(
        empirical_law,
        p75_four_view_law_exact(root_center),
    )

    serial = 0
    active: list[tuple[Fraction, int, P78ParameterBox, Fraction]] = []
    heappush(active, (root_p80, serial, root, root_p78))
    serial += 1

    best_upper = root_upper
    best_parameters = root_center
    evaluated_boxes = 1
    iterations = 0

    while len(active) < max_leaves:
        global_lower = active[0][0]
        if best_upper - global_lower <= gap_tolerance:
            break

        _, _, box, _ = heappop(active)
        if box.width_sum == 0:
            heappush(
                active,
                (
                    p75_box_simplex_linf_lower_bound_exact(empirical_law, box),
                    serial,
                    box,
                    p75_box_linf_lower_bound_exact(empirical_law, box),
                ),
            )
            break

        left, right = box.split_widest()
        for child in (left, right):
            p80_lower = p75_box_simplex_linf_lower_bound_exact(
                empirical_law,
                child,
            )
            p78_lower = p75_box_linf_lower_bound_exact(empirical_law, child)
            center = child.center
            center_upper = linf_distance_exact(
                empirical_law,
                p75_four_view_law_exact(center),
            )
            if center_upper < best_upper:
                best_upper = center_upper
                best_parameters = center
            heappush(active, (p80_lower, serial, child, p78_lower))
            serial += 1
            evaluated_boxes += 1
        iterations += 1

    global_lower = active[0][0]
    p78_active_lower = min(entry[3] for entry in active)
    maximum_width_sum = max(entry[2].width_sum for entry in active)
    p78_mesh_upper = p78_active_lower + maximum_width_sum
    certified_upper = min(best_upper, p78_mesh_upper)
    certified_gap = certified_upper - global_lower

    if certified_gap < 0:
        raise RuntimeError("certified upper bound fell below the P80 lower bound")

    if global_lower == certified_upper:
        conclusion = "exact global L-infinity model distance certified"
    elif len(active) >= max_leaves:
        conclusion = (
            "valid P80 global distance bracket; leaf budget exhausted before exact closure"
        )
    else:
        conclusion = "valid P80 global distance bracket; requested gap tolerance reached"

    return P80DistanceBracket(
        lower_bound=global_lower,
        upper_bound=certified_upper,
        best_parameters=best_parameters,
        leaf_count=len(active),
        evaluated_boxes=evaluated_boxes,
        iterations=iterations,
        maximum_active_width_sum=maximum_width_sum,
        p78_active_lower_bound=p78_active_lower,
        p78_mesh_upper_bound=p78_mesh_upper,
        certified_gap=certified_gap,
        root_p78_bound=root_p78,
        root_p80_bound=root_p80,
        root_tightening=root_p80 - root_p78,
        conclusion=conclusion,
    )


def p80_rejection_with_p79_radius(
    bracket: P80DistanceBracket,
    radius: P79SamplingRadiusCertificate,
) -> bool:
    """Apply the strict P77 rejection gate with P80/P79 certified directions."""

    return bracket.lower_bound > radius.cell_linf_radius_upper
