"""Generate, synchronize, and validate the repository's visual record.

The repository contains two deliberately distinct kinds of visual assets:

1. generated quantitative atlases under ``docs/figures/quantitative`` and
   ``docs/figures/quantum``;
2. source-controlled theorem and architecture SVGs under ``docs/figures``.

The computational atlases are regenerated by their canonical scripts. The
source-authored theorem diagrams are validated and enriched from maintained
scientific records rather than falsely presented as plotting-script output.
After the canonical figure tree is ready, ``sync_figure_publication.py`` derives
the GitHub-facing figure gateway, SHA-256 manifest, and current Visual Atlas
frontier from the same tree.

Run from the repository root with::

    python scripts/generate_all_figures.py

Use ``--validate-only`` to validate the existing SVG tree and require all public
figure surfaces to be synchronized without regenerating atlas outputs.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FIGURE_ROOT = ROOT / "docs" / "figures"
QUANTITATIVE_DIR = FIGURE_ROOT / "quantitative"
QUANTUM_DIR = FIGURE_ROOT / "quantum"
GENERATORS = (
    ROOT / "scripts" / "generate_quantitative_atlas.py",
    ROOT / "scripts" / "generate_quantum_foundations_atlas.py",
)
ENRICHER = ROOT / "scripts" / "enrich_figure_documentation.py"
PUBLICATION_SYNCER = ROOT / "scripts" / "sync_figure_publication.py"


def _run_script(path: Path, *args: str) -> None:
    if not path.is_file():
        raise FileNotFoundError(f"missing figure script: {path.relative_to(ROOT)}")
    suffix = " " + " ".join(args) if args else ""
    print(f"[figures] running {path.relative_to(ROOT)}{suffix}")
    subprocess.run([sys.executable, str(path), *args], cwd=ROOT, check=True)


def _load_json(path: Path) -> object:
    if not path.is_file():
        raise FileNotFoundError(f"missing figure manifest: {path.relative_to(ROOT)}")
    return json.loads(path.read_text(encoding="utf-8"))


def _validate_quantitative_manifest() -> int:
    manifest_path = QUANTITATIVE_DIR / "quantitative_figure_manifest.json"
    manifest = _load_json(manifest_path)
    if not isinstance(manifest, list) or not manifest:
        raise ValueError("quantitative figure manifest must be a nonempty list")

    expected = {str(item["file"]) for item in manifest if isinstance(item, dict)}
    actual = {path.name for path in QUANTITATIVE_DIR.glob("q*.svg")}
    if expected != actual:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise RuntimeError(
            "quantitative figure manifest mismatch: "
            f"missing={missing}, extra={extra}"
        )
    return len(actual)


def _validate_quantum_manifest() -> int:
    manifest_path = QUANTUM_DIR / "quantum_figure_manifest.json"
    manifest = _load_json(manifest_path)
    if not isinstance(manifest, dict):
        raise TypeError("quantum figure manifest must be an object")
    figures = manifest.get("figures")
    if not isinstance(figures, list) or not figures:
        raise ValueError("quantum figure manifest must contain a nonempty figures list")

    expected = {str(item["file"]) for item in figures if isinstance(item, dict)}
    actual = {path.name for path in QUANTUM_DIR.glob("qm*.svg")}
    declared_count = manifest.get("figure_count")
    if declared_count != len(expected):
        raise RuntimeError(
            "quantum manifest figure_count does not match the listed figure records"
        )
    if expected != actual:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        raise RuntimeError(
            f"quantum figure manifest mismatch: missing={missing}, extra={extra}"
        )
    return len(actual)


def _validate_svg_tree() -> tuple[int, int]:
    svg_paths = sorted(FIGURE_ROOT.rglob("*.svg"))
    if not svg_paths:
        raise RuntimeError("no SVG figures were found under docs/figures")

    source_authored = 0
    for path in svg_paths:
        try:
            root = ET.fromstring(path.read_text(encoding="utf-8"))
        except (OSError, ET.ParseError) as exc:
            raise RuntimeError(f"invalid SVG: {path.relative_to(ROOT)}") from exc
        if not root.tag.endswith("svg"):
            raise RuntimeError(f"not an SVG root element: {path.relative_to(ROOT)}")
        if QUANTITATIVE_DIR not in path.parents and QUANTUM_DIR not in path.parents:
            source_authored += 1

    return len(svg_paths), source_authored


def validate_figures() -> None:
    quantitative_count = _validate_quantitative_manifest()
    quantum_count = _validate_quantum_manifest()
    svg_count, source_authored_count = _validate_svg_tree()
    print(
        "[figures] validation passed: "
        f"{quantitative_count} quantitative atlas SVGs, "
        f"{quantum_count} quantum atlas SVGs, "
        f"{source_authored_count} source-authored SVGs, "
        f"{svg_count} total SVGs"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Generate the reproducible figure atlases, synchronize publication "
            "surfaces, and validate all SVG assets."
        )
    )
    parser.add_argument(
        "--validate-only",
        action="store_true",
        help=(
            "validate current figures and require publication synchronization "
            "without regenerating atlas outputs"
        ),
    )
    args = parser.parse_args()

    if args.validate_only:
        validate_figures()
        _run_script(PUBLICATION_SYNCER, "--check")
        return

    for generator in GENERATORS:
        _run_script(generator)
    _run_script(ENRICHER)
    _run_script(PUBLICATION_SYNCER)
    validate_figures()
    _run_script(PUBLICATION_SYNCER, "--check")


if __name__ == "__main__":
    main()
