from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one anchor, found {count}: {old!r}")
    return text.replace(old, new, 1)


def require(text: str, token: str, label: str) -> None:
    if token not in text:
        raise RuntimeError(f"{label}: missing required token {token!r}")


def patch_readme() -> None:
    path = "README.md"
    text = read(path)
    require(text, "## 1.11 P77: full-law confidence regions can reject the complete declared model set", path)
    if "## 1.12 P78: certified continuous separation for the P75 model family" in text:
        raise RuntimeError("README already contains P78 formal section")

    text = text.replace("0.77.0", "0.78.0")
    text = text.replace("P1 through P77", "P1 through P78")
    text = text.replace("P71-P77", "P71-P78")
    text = text.replace("P71 through P77", "P71 through P78")
    text = text.replace("77 proposition-level results", "78 proposition-level results")
    text = text.replace("65 equation-driven quantitative figures", "66 equation-driven quantitative figures")
    text = text.replace("The theorem frontier is P77.", "The theorem frontier is P78.")
    text = text.replace("| Proposition-level results | **77** |", "| Proposition-level results | **78** |")
    text = text.replace("| Equation-driven quantitative figures | **65** |", "| Equation-driven quantitative figures | **66** |")
    text = text.replace("Current documented theorem frontier: P77", "Current documented theorem frontier: P78")

    p77_plain = (
        "P77 closes the next logical gap. P76 can reject the measurement model when one of its tracked mathematical requirements fails, but a model can in principle pass those selected checks and still fail to reproduce the complete pattern of observed outcomes. P77 therefore asks a stronger question: **after finite-sample uncertainty is included, is there any distribution allowed by the entire declared measurement model that is still compatible with the data?** If the whole confidence region around the observed distribution is separated from the whole model family, the model can be rejected. If the regions still overlap, the result remains inconclusive. P77 also makes a computational safeguard explicit: finding one imperfect best-fitting model is not enough to prove separation from every model in the family. A rejection requires a mathematically certified lower bound on the distance to the model set, or an equivalent certified proof that no admissible model lies inside the confidence region. In plain language, P76 tests interpretable necessary requirements; P77 defines the stronger full-distribution standard that a complete finite-data adequacy test must satisfy.\n\n"
    )
    p78_plain = (
        "P78 addresses the computational problem that P77 deliberately leaves open for the continuous four-view target model. The P75 model does not contain a finite list of candidate distributions; it contains a continuous family generated by nine parameters. Testing a few parameter choices, or even finding an excellent numerical fit, cannot prove that every allowed model is far from the data. P78 therefore partitions the entire parameter region into boxes and computes a mathematically guaranteed lower bound for every box. Because those boxes still cover every allowed parameter choice, the smallest box bound is a genuine lower bound on the distance to the whole continuous model family. At the same time, any explicit candidate model supplies an upper bound. Refining the boxes narrows the gap between the two. The implementation keeps the empirical count law and the adaptive box boundaries in exact rational arithmetic so the global optimization certificate is not created by rounding a local floating-point optimizer. When the certified global lower bound is larger than a separately valid upper bound on the P77 sampling radius, the full continuous model family is rejected with the P77 statistical guarantee. A small lower bound remains inconclusive; P78 does not turn failure to reject into model validation.\n\n"
    )
    text = replace_once(text, p77_plain, p77_plain + p78_plain, "README plain-language P78")

    text = replace_once(
        text,
        "P77 then asks the stronger full-law question: whether the complete finite-sample confidence region is separated from the entire declared target-measurement model, while refusing to treat an uncertified local best fit as proof of global incompatibility.",
        "P77 then asks the stronger full-law question: whether the complete finite-sample confidence region is separated from the entire declared target-measurement model, while refusing to treat an uncertified local best fit as proof of global incompatibility. P78 supplies a certified continuous-family lower-bound procedure for the specific P75 model by exploiting its multi-affine parameterization and exact-rational box refinement.",
        "README synthesis P78",
    )

    p77_abstract = (
        "P77 strengthens that finite-data adequacy layer from selected necessary constraints to the complete declared observed-law model set. For a finite alphabet of size $K$, one simultaneous empirical-law event gives $\\|\\widehat P-P\\|_\\infty\\le\\varepsilon_{n,K}$ and $\\|\\widehat P-P\\|_1\\le\\delta_{n,K}$ with probability at least $1-\\alpha$. If the corresponding confidence region is disjoint from the declared model family $\\mathcal M$, equivalently if a sound lower bound on empirical distance to $\\mathcal M$ exceeds the sampling radius, the model is rejected at the same confidence level. A numerical candidate fit supplies only an upper bound on distance and cannot by itself certify rejection of a continuous model family.\n\n"
    )
    p78_abstract = (
        "P78 supplies a certified continuous-family lower bound for the P75 four-view binary latent model. Its sixteen observed cell probabilities are multi-affine functions of nine parameters. On every axis-aligned parameter box, exact coordinatewise cell ranges give a rigorous lower bound $L_\\infty(B;\\widehat P)$ on the distance from the empirical law to every model law generated in that box. For any finite box partition $\\mathcal B$ of the complete parameter cube, $L_{\\mathcal B}=\\min_{B\\in\\mathcal B}L_\\infty(B;\\widehat P)$ is therefore a valid global lower bound on $d_\\infty(\\widehat P,\\mathcal M_{4,2})$. An explicit parameter point gives an upper bound, and a parameter-space Lipschitz argument gives the mesh guarantee $0\\le d_\\infty-L_{\\mathcal B}\\le\\eta(\\mathcal B)$. The implementation uses exact rational arithmetic for empirical counts and dyadic box refinement. P78 is a computational certification theorem under the declared P75 model, not an experiential ontology.\n\n"
    )
    text = replace_once(text, p77_abstract, p77_abstract + p78_abstract, "README abstract P78")

    # Repair the existing duplicate numbering first, then make room for P78 as Figure 13.
    text = replace_once(text, "**Figure 13. P77 full-law model-set separation.**", "**Figure 12. P77 full-law model-set separation.**", "README P77 figure number")
    for number in range(25, 12, -1):
        text = text.replace(f"**Figure {number}.", f"**Figure {number + 1}.")

    marker = "Direct proof: [Proposition 77](docs/proposition_77_full_law_model_set_separation.md). Equation and literature classification: [P77 provenance record](docs/p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](src/consciousness_bridge/full_law_model_set_separation.py). Tests: [`test_full_law_model_set_separation.py`](tests/test_full_law_model_set_separation.py).\n\n\n\n---\n\n# 2. From physical dynamics to operational structure"
    p78_section = """Direct proof: [Proposition 77](docs/proposition_77_full_law_model_set_separation.md). Equation and literature classification: [P77 provenance record](docs/p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](src/consciousness_bridge/full_law_model_set_separation.py). Tests: [`test_full_law_model_set_separation.py`](tests/test_full_law_model_set_separation.py).

## 1.12 P78: certified continuous separation for the P75 model family

P77 says that full-law rejection requires a sound lower bound on distance to the complete declared model set. P78 constructs such a bound for the continuous P75 four-view binary latent family.

Let

$$
\\theta=(\\pi,q_{1,-},q_{1,+},\\ldots,q_{4,-},q_{4,+})\\in[0,1]^9
$$

parameterize the P75 model law $F(\\theta)$. Every observed cell probability is multi-affine in these nine parameters. For an axis-aligned parameter box $B$, P78 computes the exact cell interval

$$
I_x(B)=[m_x(B),M_x(B)]
$$

and defines

$$
\\boxed{L_\\infty(B;\\widehat P)=\\max_x\\operatorname{dist}(\\widehat P(x),I_x(B)).}
$$

For every $\\theta\\in B$,

$$
\\|\\widehat P-F(\\theta)\\|_\\infty\\ge L_\\infty(B;\\widehat P).
$$

If $\\mathcal B$ is any finite partition of the complete parameter cube, then

$$
\\boxed{L_{\\mathcal B}(\\widehat P):=\\min_{B\\in\\mathcal B}L_\\infty(B;\\widehat P)\\le d_\\infty(\\widehat P,\\mathcal M_{4,2}).}
$$

Any explicit admissible parameter vector supplies an upper bound on the same minimum distance. In addition, every cell map is 1-Lipschitz with respect to parameter $L^1$, giving the mesh certificate

$$
\\boxed{0\\le d_\\infty(\\widehat P,\\mathcal M_{4,2})-L_{\\mathcal B}(\\widehat P)\\le\\eta(\\mathcal B),}
$$

where $\\eta(\\mathcal B)$ is the largest summed side width among active boxes. Refinement therefore closes the certified optimization gap.

The implementation uses exact `Fraction` arithmetic for empirical count laws and dyadic branch points. This protects the optimization lower-bound direction from ordinary floating-point local-fit claims. Statistical rejection still requires a separately valid upper bound on the P77 sampling radius.

![P78 certified continuous model separation](docs/figures/p78_certified_continuous_model_separation.svg)

**Figure 13. P78 certified continuous model separation.** The complete nine-parameter P75 cube is covered by adaptive boxes. Exact multi-affine cell enclosures produce boxwise lower bounds, their minimum is a global lower bound, and explicit admissible parameters supply upper bounds. P77 rejection is triggered only when the certified global lower bound exceeds a valid sampling-radius upper bound.

Direct proof: [Proposition 78](docs/proposition_78_certified_continuous_model_separation.md). Equation and literature classification: [P78 provenance record](docs/p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](tests/test_certified_continuous_model_separation.py).



---

# 2. From physical dynamics to operational structure"""
    text = replace_once(text, marker, p78_section, "README formal P78")

    text = replace_once(
        text,
        "P77 upgrades the finite-data target to the complete declared observed-law model set through confidence-region separation. The remaining challenge is computational certification of global distance or feasibility for the continuous P75 latent family, together with sharper power and broader dependent-view alternatives.",
        "P77 upgrades the finite-data target to the complete declared observed-law model set through confidence-region separation. P78 then supplies an exact-rational branch-and-bound lower-bound certificate for the continuous P75 latent family. The remaining challenges are faster and tighter global certification, sharper power, and broader dependent-view alternatives.",
        "README finite experiment P78",
    )

    text = text.replace("This branch remains intentionally separate from P71-P77.", "This branch remains intentionally separate from P71-P78.")

    established_anchor = "P77 strengthens finite-sample adequacy to the complete declared observed-law model set: confidence-region/model-set separation certifies rejection, but only when model distance or infeasibility is lower-bounded soundly."
    require(text, established_anchor, "README established P77")
    text = text.replace(
        established_anchor,
        established_anchor + "\n20. P78 supplies a certified global L-infinity lower bound for the continuous P75 family by exact-rational multi-affine box refinement, with an explicit mesh-gap guarantee and a direct P77 rejection handoff.",
        1,
    )
    text = text.replace("\n20. The experiment-design branch", "\n21. The experiment-design branch", 1)

    # Replace the immediate-frontier paragraph without depending on its full wording.
    text = re.sub(
        r"The most immediate target-side problem after P77 is \*\*certified computation and power for full-law adequacy\*\*\.[^\n]*\n",
        "The most immediate target-side problem after P78 is **tighter certified computation and power for full-law adequacy**. P78 supplies a rigorous exact-rational branch-and-bound lower bound for the continuous P75 family, but the nine-dimensional search can be expensive. The next methodological target is stronger certified pruning or relaxation, potentially using interval tightening or polynomial moment-SOS lower bounds, together with sharper power analysis and broader target-view dependence models.\n",
        text,
        count=1,
    )

    p77_falsification = "| Full-law finite data reject the target model | A P77 confidence region is certified disjoint from the complete declared model set | Treating a local best-fit optimizer value as a certified global distance lower bound |"
    p78_falsification = "| Continuous P75 full-law separation is certified | A P78 global lower bound exceeds a valid P77 sampling-radius upper bound | Treating an incomplete parameter search or ordinary floating approximation as a formal certificate |"
    text = replace_once(text, p77_falsification, p77_falsification + "\n" + p78_falsification, "README falsification P78")

    p77_prov = "| [P77 equation and provenance record](docs/p77_equation_provenance.md) | Full-law confidence-region inversion, model-set distance transport, and certified lower-bound rejection provenance |"
    p78_prov = "| [P78 equation and provenance record](docs/p78_equation_provenance.md) | Multi-affine box enclosures, global branch-and-bound lower bounds, mesh-gap certification, and P77 handoff provenance |"
    text = replace_once(text, p77_prov, p77_prov + "\n" + p78_prov, "README provenance P78")

    p77_status = "| Full-law finite-sample target-model adequacy | **P77 proved as a confidence-region/model-set separation theorem, conditional on a sound distance lower bound or equivalent certified feasibility result** |"
    p78_status = "| Continuous-family full-law optimization certificate | **P78 proved for the P75 four-view binary latent family using exact-rational multi-affine box lower bounds and an explicit mesh-gap guarantee** |"
    text = replace_once(text, p77_status, p77_status + "\n" + p78_status, "README status P78")

    p77_nav = "| Inspect finite-sample full-law model-set separation | [P77](docs/proposition_77_full_law_model_set_separation.md) |"
    p78_nav = "| Inspect certified continuous P75 model separation | [P78](docs/proposition_78_certified_continuous_model_separation.md) |"
    text = replace_once(text, p77_nav, p77_nav + "\n" + p78_nav, "README nav P78")

    p77_audit = "| Audit P77 full-law separation equations | [P77 equation and provenance record](docs/p77_equation_provenance.md) |"
    p78_audit = "| Audit P78 continuous-separation equations | [P78 equation and provenance record](docs/p78_equation_provenance.md) |"
    text = replace_once(text, p77_audit, p77_audit + "\n" + p78_audit, "README audit P78")

    text = text.replace(
        "full-law model-set separation, admissible bridge class",
        "full-law model-set separation, certified continuous model separation, admissible bridge class",
    )
    write(path, text)


def patch_citation_guide() -> None:
    path = "CITATION.md"
    text = read(path)
    text = text.replace("0.77.0", "0.78.0")
    text = text.replace("frontier, P77", "frontier, P78")
    text = text.replace("frontier: P77", "frontier: P78")
    text = text.replace("frontier **P77**", "frontier **P78**")
    text = text.replace("P1 through P77 chronological theorem record", "P1 through P78 chronological theorem record")

    p77_specific = "Cite [Proposition 77](docs/proposition_77_full_law_model_set_separation.md) when relying on finite-sample confidence-region separation from the complete declared model set, 1-Lipschitz transport of model distance, fixed-margin design bounds, or the requirement that rejection of a continuous family use a certified distance lower bound or equivalent feasibility proof rather than an ordinary best-fit upper bound."
    p78_specific = " Cite [Proposition 78](docs/proposition_78_certified_continuous_model_separation.md) when relying on the exact multi-affine box enclosure for the P75 model, the certified continuous-family L-infinity lower bound, the mesh-gap convergence guarantee, the exact-rational branch-and-bound implementation, or its strict P77 rejection handoff."
    text = replace_once(text, p77_specific, p77_specific + p78_specific, "CITATION P78 specific")

    p77_scope = "P77 then extends finite-data adequacy from selected necessary constraints to the complete declared observed-law model set. It inverts the simultaneous empirical-law confidence region against that model set and permits rejection only when the confidence region is certified disjoint from the model family. For continuous latent models, an ordinary candidate fit is only an upper bound on the minimum model distance, so P77 requires a sound lower bound or equivalent certified feasibility result before claiming full-law incompatibility.\n\n"
    p78_scope = "P78 supplies that missing continuous-family lower-bound mechanism for the specific P75 four-view binary latent model. It exploits the model's multi-affine nine-parameter map to compute exact rational cell enclosures on parameter boxes, aggregates those into a global L-infinity lower bound, and proves a mesh-width convergence guarantee. P78 remains a computational certificate under the declared P75 model; it does not turn non-rejection into model validation or identify the latent state with consciousness.\n\n"
    text = replace_once(text, p77_scope, p77_scope + p78_scope, "CITATION P78 scope")

    p77_resource = "- [P77 equation and provenance record](docs/p77_equation_provenance.md): full-law confidence-region inversion, model-distance transport, and certified lower-bound rejection provenance."
    p78_resource = "- [P78 equation and provenance record](docs/p78_equation_provenance.md): multi-affine box enclosures, exact-rational global lower bounds, mesh-gap convergence, and P77 rejection handoff provenance."
    text = replace_once(text, p77_resource, p77_resource + "\n" + p78_resource, "CITATION P78 resource")
    write(path, text)


def patch_roadmap() -> None:
    path = "docs/theorem_roadmap.md"
    text = read(path)
    text = text.replace("frontier is **P77**", "frontier is **P78**")
    text = text.replace("P1 through P77", "P1 through P78")
    text = text.replace("P71-P77", "P71-P78")
    text = replace_once(
        text,
        "&\\text{P77: full-law confidence regions must be separated from the complete declared model set}\n\\end{aligned}",
        "&\\text{P77: full-law confidence regions must be separated from the complete declared model set}\\\\\n&\\Downarrow\\\\\n&\\text{P78: continuous P75 model distance must be lower-bounded globally and certifiably}\n\\end{aligned}",
        "roadmap dependency P78",
    )
    text = text.replace(
        "It does not imply that P77 depends on P70. P77 depends scientifically on P76 and P75, which in turn descend from P19 and the P71-P74 target-side lineage.",
        "It does not imply that P78 depends on P70. P78 depends scientifically on P77 and the P75 continuous target-model family, which descend from P19 and the P71-P76 target-side lineage.",
    )

    marker = "Direct proof: [P77](proposition_77_full_law_model_set_separation.md). Provenance: [P77 equation record](p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](../src/consciousness_bridge/full_law_model_set_separation.py). Tests: [`test_full_law_model_set_separation.py`](../tests/test_full_law_model_set_separation.py).\n\n\n## 3. Complete proposition index"
    section = """Direct proof: [P77](proposition_77_full_law_model_set_separation.md). Provenance: [P77 equation record](p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](../src/consciousness_bridge/full_law_model_set_separation.py). Tests: [`test_full_law_model_set_separation.py`](../tests/test_full_law_model_set_separation.py).

### P78: certified continuous separation for the P75 model family

P77 requires a certified lower bound on empirical distance to the complete model family. For the continuous P75 four-view binary latent model, P78 writes the observed-law map as a nine-parameter multi-affine map \(F:[0,1]^9\to\Delta_{15}\). On each parameter box \(B\), exact cell intervals produce

\[
L_\infty(B;\widehat P)
=
\max_x\operatorname{dist}(\widehat P(x),I_x(B))
\le
\inf_{\theta\in B}\|\widehat P-F(\theta)\|_\infty.
\]

For any finite partition \(\mathcal B\) of the full parameter cube,

\[
\boxed{L_{\mathcal B}:=\min_{B\in\mathcal B}L_\infty(B;\widehat P)
\le d_\infty(\widehat P,\mathcal M_{4,2}).}
\]

An explicit admissible parameter point provides an upper bound. The cell maps are 1-Lipschitz in parameter \(L^1\), giving

\[
\boxed{0\le d_\infty-L_{\mathcal B}\le\eta(\mathcal B).}
\]

The implementation uses exact rational arithmetic for empirical counts and dyadic box refinement. A P77 rejection is certified only when the P78 lower bound exceeds a separately valid upper bound on the P77 sampling radius.

![P78 certified continuous model separation](figures/p78_certified_continuous_model_separation.svg)

Direct proof: [P78](proposition_78_certified_continuous_model_separation.md). Provenance: [P78 equation record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](../tests/test_certified_continuous_model_separation.py).


## 3. Complete proposition index"""
    text = replace_once(text, marker, section, "roadmap formal P78")

    row = "| [P77](proposition_77_full_law_model_set_separation.md) | confidence-region/model-set separation | finite-sample full-law rejection with certified distance lower bounds | proved conditional theorem |"
    newrow = "| [P78](proposition_78_certified_continuous_model_separation.md) | multi-affine box lower bounds and mesh-gap convergence | certified continuous P75 full-law model separation | proved conditional computational theorem |"
    text = replace_once(text, row, row + "\n" + newrow, "roadmap index P78")

    open_start = text.index("## 5. Current open frontier")
    text = text[:open_start] + """## 5. Current open frontier

After P78, the target side has eight explicit requirements:

1. the target must have non-circular provenance relative to the tested physical descriptor;
2. its observation channel must be valid and sufficiently informative for the claimed witness;
3. channel reliability must be identified or externally calibrated under a defensible target-measurement model;
4. finite data must resolve the channel parameters far enough from the model singularity to support a confidence-certified reliability statement;
5. the target-measurement model itself must survive adequacy tests rather than being accepted because it can be fit;
6. finite data must separate a genuine adequacy violation from sampling uncertainty before model rejection is claimed;
7. complete full-law rejection must be defined against the whole declared model family, not only selected necessary constraints;
8. when the declared family is continuous, the required separation distance must be lower-bounded globally rather than inferred from a local best fit.

P78 closes the eighth item for the specific P75 four-view binary latent family in L-infinity distance. It supplies an exact-rational multi-affine box certificate and an explicit mesh-gap guarantee. The remaining computational problem is efficiency: stronger pruning, tighter relaxations, or moment-SOS lower bounds may reduce the number of boxes required for a decisive certificate. The remaining statistical problems include sharper power and target-view models that allow residual dependence, shared bias, temporal drift, or learned measurement pipelines.

None of these results identifies a latent variable with consciousness. The physical-to-experiential bridge remains open.
"""
    write(path, text)


def patch_navigation() -> None:
    path = "docs/research_navigation.md"
    text = read(path)
    text = text.replace("frontier is **P77**", "frontier is **P78**")
    text = text.replace("P1 through P77", "P1 through P78")
    text = text.replace("P71-P77", "P71-P78")

    for number in range(24, 13, -1):
        text = text.replace(f"\n{number}. ", f"\n{number + 1}. ")
    p77_item = "13. [P77 finite-sample full-law model-set separation](proposition_77_full_law_model_set_separation.md) for confidence-region separation from the complete declared model family, model-distance transport, and the certified-lower-bound requirement for continuous-family rejection."
    p78_item = "14. [P78 certified continuous P75 model separation](proposition_78_certified_continuous_model_separation.md) for exact multi-affine box enclosures, global L-infinity distance lower bounds, mesh-gap convergence, and the strict P77 rejection handoff."
    text = replace_once(text, p77_item, p77_item + "\n" + p78_item, "navigation P78 order")

    p77_branch = "| Full-law finite-sample target-model adequacy | P77 | Inverts the complete empirical-law confidence region against the declared model set and requires certified global separation for rejection | [P77](proposition_77_full_law_model_set_separation.md) |"
    p78_branch = "| Certified continuous target-model separation | P78 | Supplies exact-rational global lower bounds for distance to the continuous P75 model family and a convergent mesh certificate | [P78](proposition_78_certified_continuous_model_separation.md) |"
    text = replace_once(text, p77_branch, p77_branch + "\n" + p78_branch, "navigation branch P78")

    row = "| P77 | [Full-law model-set separation](proposition_77_full_law_model_set_separation.md) | finite-sample confidence-region separation from the complete declared model family |"
    newrow = "| P78 | [Certified continuous model separation](proposition_78_certified_continuous_model_separation.md) | exact-rational global lower bound for the continuous P75 model family |"
    text = replace_once(text, row, row + "\n" + newrow, "navigation index P78")

    # Add provenance routes near the end of the recommended list.
    citation_item = "25. [Citation guide](../CITATION.md) for citing the whole research program or a specific proposition, figure, algorithm, or implementation."
    if citation_item in text:
        text = text.replace(
            citation_item,
            "25. [P78 equation and provenance record](p78_equation_provenance.md) for multi-affine box bounds, global distance certification, and the P77 handoff.\n26. [Citation guide](../CITATION.md) for citing the whole research program or a specific proposition, figure, algorithm, or implementation.",
            1,
        )
    write(path, text)


def patch_detail() -> None:
    path = "docs/detailed_proposition_record.md"
    text = read(path)
    text = text.replace("Complete P1 to P77 chronology", "Complete P1 to P78 chronology")
    marker = "Direct P77 proof: [finite-sample full-law model-set separation](proposition_77_full_law_model_set_separation.md). Equation classification: [P77 equation and provenance record](p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](../src/consciousness_bridge/full_law_model_set_separation.py).\n\n\n---\n"
    section = """Direct P77 proof: [finite-sample full-law model-set separation](proposition_77_full_law_model_set_separation.md). Equation classification: [P77 equation and provenance record](p77_equation_provenance.md). Implementation: [`full_law_model_set_separation.py`](../src/consciousness_bridge/full_law_model_set_separation.py).

**P78** supplies the continuous-family optimization certificate required by P77 for the specific P75 four-view binary latent model. Each of the sixteen cell probabilities is multi-affine in nine parameters. On every axis-aligned parameter box, P78 computes exact coordinatewise cell ranges and converts them into a rigorous L-infinity lower bound on the distance from the empirical law to every model law generated inside that box.

Because the active boxes form a partition of the complete parameter cube, the minimum active-box lower bound is a global lower bound on distance to the entire continuous P75 model family. Explicit admissible parameter vectors provide upper bounds. A parameter-space Lipschitz argument gives an explicit mesh-gap certificate, so the global lower bound converges under refinement. The implementation keeps empirical count laws and dyadic branch points in exact rational arithmetic.

The P77 handoff remains directional: full-law rejection requires the P78 global lower bound to exceed a separately valid upper bound on the P77 sampling radius. A small lower bound is inconclusive and does not validate the target model.

Direct P78 proof: [certified continuous model separation](proposition_78_certified_continuous_model_separation.md). Equation classification: [P78 equation and provenance record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py).


---
"""
    text = replace_once(text, marker, section, "detail P78")
    text = text.replace("P71-P77 return to the target side", "P71-P78 return to the target side")
    text = replace_once(
        text,
        "P76 adds a finite-sample rejection layer for a tracked family of necessary P75 polynomial constraints. Its non-rejection output is explicitly inconclusive. P77 then defines the stronger finite-sample full-law criterion by asking whether the complete confidence region is separated from the complete declared model family. Its next computational problem is certified global lower-bounding or feasibility for the continuous P75 latent model, followed by sharper power and robust alternatives for residually dependent or learned target-view systems.",
        "P76 adds a finite-sample rejection layer for a tracked family of necessary P75 polynomial constraints. Its non-rejection output is explicitly inconclusive. P77 then defines the stronger finite-sample full-law criterion by asking whether the complete confidence region is separated from the complete declared model family. P78 supplies the missing global lower-bound certificate for the continuous P75 latent family using exact-rational multi-affine box refinement. The next problems are computational efficiency, sharper power, and robust alternatives for residually dependent or learned target-view systems.",
        "detail interpretation P78",
    )
    write(path, text)


def patch_equation_map() -> None:
    path = "docs/equation_and_citation_map.md"
    text = read(path)
    if "# P78 certified continuous model separation" in text:
        raise RuntimeError("equation map already contains P78")
    text = text.rstrip() + """

# P78 certified continuous model separation

P78 supplies a computable global lower-bound mechanism for the continuous P75 four-view binary latent family required by the P77 rejection theorem.

- **Multi-affine observed-law map:** each of the sixteen P75 cell probabilities is affine in each of the nine parameters with all others held fixed.
  **Status:** direct algebraic property of the standard latent-class parameterization; multi-affine box-extremum principles are standard.

- **Exact box cell enclosure:**
  \[
  I_x(B)=[m_x(B),M_x(B)].
  \]
  **Status:** standard endpoint/vertex extremum property specialized to the P75 product structure.

- **Certified box lower bound:**
  \[
  L_\infty(B;\widehat P)=\max_x\operatorname{dist}(\widehat P(x),I_x(B))
  \le\inf_{\theta\in B}\|\widehat P-F(\theta)\|_\infty.
  \]
  **Status:** elementary interval lower bound.

- **Global partition lower bound:**
  \[
  L_{\mathcal B}=\min_{B\in\mathcal B}L_\infty(B;\widehat P)
  \le d_\infty(\widehat P,\mathcal M_{4,2}).
  \]
  **Status:** standard branch-and-bound aggregation, integrated here with P77.

- **Mesh-gap certificate:**
  \[
  0\le d_\infty(\widehat P,\mathcal M_{4,2})-L_{\mathcal B}\le\eta(\mathcal B).
  \]
  **Status:** repository-specific specialization from the P75 derivative bounds and box enclosure.

- **P77 handoff:** a certified P78 lower bound may trigger P77 only when it exceeds a separately valid upper bound on the sampling radius.
  **Status:** repository-specific composition preserving the required inequality directions.

Proof: [P78](proposition_78_certified_continuous_model_separation.md). Dedicated provenance: [P78 equation and provenance record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](../tests/test_certified_continuous_model_separation.py).

The physical-to-experiential bridge remains open.
"""
    write(path, text)


def patch_changelog() -> None:
    path = "CHANGELOG.md"
    text = read(path)
    if text.startswith("# 0.78.0 - 2026-09-10"):
        raise RuntimeError("changelog already contains P78")
    entry = """# 0.78.0 - 2026-09-10

## Proposition 78: certified continuous model separation

- closes the continuous-model optimization gap left explicit by P77 for the P75 four-view binary latent family;
- exposes the exact nine-parameter multi-affine structure of the sixteen-cell P75 observed-law map;
- derives exact coordinatewise cell enclosures on axis-aligned parameter boxes;
- converts those enclosures into certified L-infinity lower bounds on distance to every model law inside each box;
- aggregates active-box bounds into a global lower bound over the complete continuous parameter cube;
- derives an explicit mesh-gap convergence guarantee from the parameter-to-law Lipschitz bound;
- implements exact-rational branch-and-bound for empirical count laws and dyadic box refinement;
- preserves the P77 distinction between certified lower bounds and candidate-model upper bounds;
- keeps the statistical sampling-radius certificate separate from the optimization certificate;
- adds the P78 proof, provenance record, theorem figure, geometry guard, implementation, tests, and public research integration;
- keeps non-rejection explicitly inconclusive and keeps the physical-to-experiential bridge open.

"""
    write(path, entry + text)


def patch_website_index() -> None:
    path = "website/index.html"
    text = read(path)
    text = text.replace("v0.77.0", "v0.78.0")
    text = text.replace("<strong>77</strong><span>proposition-level results</span>", "<strong>78</strong><span>proposition-level results</span>")
    text = text.replace("all 77 results", "all 78 results")
    text = text.replace("P71-P77", "P71-P78")
    text = text.replace("P1-P77", "P1-P78")

    if "p78_certified_continuous_model_separation.svg" not in text:
        block = """
    <section class="section">
      <div class="section-head"><p class="eyebrow">P78 computational frontier</p><h2>Certified continuous P75 model separation</h2><p>P77 requires a sound global lower bound before a continuous model family can be rejected. P78 supplies one for the P75 four-view binary latent family using exact-rational multi-affine box refinement. Explicit model points remain upper bounds; only the certified lower side can trigger the P77 rejection gate.</p></div>
      <div class="figure-card"><img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p78_certified_continuous_model_separation.svg" alt="P78 certified continuous model separation"/><div><h3>P78 theorem figure</h3><p>Adaptive parameter boxes cover the full nine-dimensional P75 cube. Exact cell enclosures yield boxwise lower bounds, their minimum is globally valid, and the mesh width controls the remaining optimization gap.</p><a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_78_certified_continuous_model_separation.md">Read Proposition 78 →</a></div></div>
    </section>

"""
        text = replace_once(text, "</main>", block + "</main>", "website P78")
    write(path, text)


def patch_research_map() -> None:
    path = "website/research-map.html"
    text = read(path)
    text = text.replace("P71-P77", "P71-P78")
    text = text.replace("P1-P77", "P1-P78")
    text = text.replace("P1 through P77", "P1 through P78")
    text = text.replace("77 results", "78 results")
    if "P78: Certified continuous P75 model separation" not in text:
        block = """
    <section class="boundary">
      <h2>P78: Certified continuous P75 model separation</h2>
      <p>P77 defines the full-law rejection criterion. P78 makes that criterion computationally certifiable for the continuous P75 four-view binary latent family by covering the complete nine-parameter cube with boxes whose exact multi-affine cell ranges give rigorous global L-infinity distance lower bounds.</p>
      <p>Candidate models still provide only upper bounds. A P77 rejection is triggered only when the P78 global lower bound exceeds a separately valid sampling-radius upper bound.</p>
      <p><a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_78_certified_continuous_model_separation.md">Read Proposition 78</a></p>
      <img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p78_certified_continuous_model_separation.svg" alt="P78 certified continuous model separation" />
    </section>

"""
        text = replace_once(text, "</main>", block + "</main>", "research map P78")
    write(path, text)


def patch_visual_atlas() -> None:
    path = "website/visual-atlas.html"
    text = read(path)
    if "p78_certified_continuous_model_separation.svg" not in text:
        block = """
    <section class="figure-card">
      <img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p78_certified_continuous_model_separation.svg" alt="P78 certified continuous model separation" />
      <div>
        <p class="eyebrow">P78</p>
        <h2>Certified Continuous P75 Model Separation</h2>
        <p>The figure shows the exact-rational branch-and-bound bridge between P77's statistical rejection theorem and the continuous P75 latent family. Boxwise multi-affine enclosures give the lower side of the model-distance bracket; explicit model points give the upper side.</p>
        <a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_78_certified_continuous_model_separation.md">Open the P78 proof</a>
      </div>
    </section>

"""
        text = replace_once(text, "</main>", block + "</main>", "visual atlas P78")
    write(path, text)


def main() -> None:
    patch_readme()
    patch_citation_guide()
    patch_roadmap()
    patch_navigation()
    patch_detail()
    patch_equation_map()
    patch_changelog()
    patch_website_index()
    patch_research_map()
    patch_visual_atlas()
    print("P78 publication patch: PASS")


if __name__ == "__main__":
    main()
