from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read(path: str) -> str:
    return (ROOT / path).read_text(encoding="utf-8")


def write(path: str, text: str) -> None:
    (ROOT / path).write_text(text, encoding="utf-8")


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f"{label}: expected one anchor, found {count}: {old!r}")
    return text.replace(old, new, 1)


def require(text: str, token: str, label: str) -> None:
    if token not in text:
        raise RuntimeError(f"{label}: missing {token!r}")


def patch_readme() -> None:
    path = "README.md"
    text = read(path)
    require(text, "## 1.12 P78: certified continuous separation for the P75 model family", path)
    if "## 1.13 P79:" in text:
        raise RuntimeError("README already contains P79 formal section")

    text = text.replace("version-0.78.0-2563eb", "version-0.79.0-2563eb")
    text = text.replace("Version 0.78.0", "Version 0.79.0")
    text = text.replace("version      = {0.78.0}", "version      = {0.79.0}")
    text = text.replace("78 proposition-level results", "79 proposition-level results")
    text = text.replace("66 equation-driven quantitative figures", "67 equation-driven quantitative figures")
    text = text.replace("The theorem frontier is P78.", "The theorem frontier is P79.")
    text = text.replace("P1 through P78 with explicit dependency branches", "P1 through P79 with explicit dependency branches")
    text = text.replace("P1 through P78", "P1 through P79")
    text = text.replace("P1 to P78", "P1 to P79")
    text = text.replace("P71-P78", "P71-P79")
    text = text.replace("P71 through P78", "P71 through P79")
    text = text.replace("P19-P24, P71-P78", "P19-P24, P71-P79")
    text = text.replace("| Public theorem frontier | **P78** |", "| Public theorem frontier | **P79** |")
    text = text.replace("| Documented version | **v0.78.0** |", "| Documented version | **v0.79.0** |")
    text = text.replace("| Proposition-level results | **78** |", "| Proposition-level results | **79** |")
    text = text.replace("| Equation-driven quantitative figures | **66** |", "| Equation-driven quantitative figures | **67** |")
    text = text.replace("Current documented theorem frontier: P78", "Current documented theorem frontier: P79")

    p78_plain = (
        "P78 addresses the computational problem that P77 deliberately leaves open for the continuous four-view target model. The P75 model does not contain a finite list of candidate distributions; it contains a continuous family generated by nine parameters. Testing a few parameter choices, or even finding an excellent numerical fit, cannot prove that every allowed model is far from the data. P78 therefore partitions the entire parameter region into boxes and computes a mathematically guaranteed lower bound for every box. Because those boxes still cover every allowed parameter choice, the smallest box bound is a genuine lower bound on the distance to the whole continuous model family. At the same time, any explicit candidate model supplies an upper bound. Refining the boxes narrows the gap between the two. The implementation keeps the empirical count law and the adaptive box boundaries in exact rational arithmetic so the global optimization certificate is not created by rounding a local floating-point optimizer. When the certified global lower bound is larger than a separately valid upper bound on the P77 sampling radius, the full continuous model family is rejected with the P77 statistical guarantee. A small lower bound remains inconclusive; P78 does not turn failure to reject into model validation.\n\n"
    )
    p79_plain = (
        "P79 addresses another assumption behind that target-measurement model: the repeated target views may retain some residual dependence even after conditioning on the latent target state. Instead of pretending that this dependence is exactly zero, P79 allows the protocol to declare or independently calibrate a quantitative dependence allowance. That allowance bounds how far residual dependence could move the observed distribution away from the conditionally independent P75 model family. A rejection therefore has to clear two margins at once: ordinary sampling uncertainty and the allowed residual dependence. If the certified P78 separation is still larger than both, the bounded-dependence extension is rejected. If it is not, the result remains inconclusive. The allowance itself must not be chosen from the same discrepancy merely to avoid rejection; it has to come from an independent scientific justification or a rule declared before the test.\n\n"
    )
    text = replace_once(text, p78_plain, p78_plain + p79_plain, "README P79 plain language")

    text = replace_once(
        text,
        "P78 supplies a certified continuous-family lower-bound procedure for the specific P75 model by exploiting its multi-affine parameterization and exact-rational box refinement. Others examine changes of physical scale, test quantum descriptions, design experiments, protect validity under adaptive sampling, or make experiments more efficient.",
        "P78 supplies a certified continuous-family lower-bound procedure for the specific P75 model by exploiting its multi-affine parameterization and exact-rational box refinement. P79 then makes the same rejection architecture robust to an independently justified amount of residual dependence among the target views instead of requiring exact conditional independence. Others examine changes of physical scale, test quantum descriptions, design experiments, protect validity under adaptive sampling, or make experiments more efficient.",
        "README synthesis P79",
    )

    abstract_anchor = (
        "P78 closes the continuous-family computational gap left by P77 for the P75 model. Its nine-parameter observed-law map is multi-affine, so every parameter box yields exact coordinatewise cell intervals and a rigorous L-infinity lower bound on distance from the empirical law to all model laws generated inside that box. The minimum lower bound over a complete box partition is therefore a valid global lower bound on distance to the continuous model family. Explicit parameter points provide upper bounds, an explicit mesh-width bound controls the optimization gap, and the implementation uses exact rational arithmetic for empirical count laws and dyadic branch points. Full-law rejection still requires the certified P78 lower bound to exceed a separately valid upper bound on the P77 sampling radius.\n\n"
    )
    p79_abstract = (
        "P79 weakens exact target-view conditional independence quantitatively. For each latent target state, let $R_s$ be the true four-view conditional law and let $\\Pi_s$ be the product of its one-view marginals. With $\\delta_s^{(p)}=\\|R_s-\\Pi_s\\|_p$ and $\\rho_p=(1-\\pi)\\delta_-^{(p)}+\\pi\\delta_+^{(p)}$, the observed population law satisfies $d_p(P,\\mathcal M_{4,2})\\le\\rho_p$. If an independently justified allowance gives $\\rho_p\\le\\bar\\rho_p$, a certified empirical model-distance lower bound $L_p$ and valid sampling-radius upper bound $\\varepsilon_p$ reject the bounded-dependence extension whenever $L_p>\\varepsilon_p+\\bar\\rho_p$. The dependence allowance must not be tuned from the same discrepancy merely to avoid rejection, and non-rejection remains inconclusive.\n\n"
    )
    text = replace_once(text, abstract_anchor, abstract_anchor + p79_abstract, "README P79 abstract")

    p78_end = (
        "Direct proof: [Proposition 78](docs/proposition_78_certified_continuous_model_separation.md). Equation and literature classification: [P78 provenance record](docs/p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](tests/test_certified_continuous_model_separation.py).\n\n\n\n---\n\n# 2. From physical dynamics to operational structure"
    )
    p79_section = """Direct proof: [Proposition 78](docs/proposition_78_certified_continuous_model_separation.md). Equation and literature classification: [P78 provenance record](docs/p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](tests/test_certified_continuous_model_separation.py).

## 1.13 P79: bounded target-view dependence does not automatically erase rejection

P75-P78 use conditional independence of the four target views given the latent target state. P79 replaces exact independence by a declared quantitative robustness allowance.

For each latent state $s$, let $R_s$ be the true conditional joint view law and let

$$
\\Pi_s(x)=\\prod_{j=1}^4R_{s,j}(x_j)
$$

be the product of its own one-view marginals. Define

$$
\\delta_s^{(p)}=\\|R_s-\\Pi_s\\|_p,
\\qquad
\\boxed{\\rho_p=(1-\\pi)\\delta_-^{(p)}+\\pi\\delta_+^{(p)}.}
$$

If $P=(1-\\pi)R_-+\\pi R_+$ is the observed population law and $Q=(1-\\pi)\\Pi_-+\\pi\\Pi_+$ is its conditionally independent counterpart, then $Q\\in\\mathcal M_{4,2}$ and

$$
\\boxed{d_p(P,\\mathcal M_{4,2})\\le\\|P-Q\\|_p\\le\\rho_p.}
$$

Suppose an external or preregistered protocol justifies $\\rho_p\\le\\bar\\rho_p$, P78 supplies a certified empirical lower bound $L_p$, and P77 supplies a valid sampling-radius upper bound $\\varepsilon_p$. Distance to a nonempty model set is 1-Lipschitz, so

$$
\\boxed{L_p>\\varepsilon_p+\\bar\\rho_p
\\quad\\Longrightarrow\\quad
\\text{reject the bounded-dependence extension}.}
$$

The dependence allowance is part of the declared target-measurement protocol. It cannot be selected after seeing the same P78 discrepancy merely to prevent rejection. A failure to clear the robust threshold remains inconclusive.

![P79 bounded target-view dependence](docs/figures/p79_bounded_target_view_dependence.svg)

**Figure 14. P79 bounded target-view dependence robustness.** Residual dependence is quantified relative to the product projection within each latent target state, transported into an observed-law neighborhood around P75, and added to the P77 sampling allowance. Robust rejection requires the P78 certified separation to exceed both allowances.

Direct proof: [Proposition 79](docs/proposition_79_bounded_target_view_dependence.md). Equation and literature classification: [P79 provenance record](docs/p79_equation_provenance.md). Implementation: [`bounded_target_view_dependence.py`](src/consciousness_bridge/bounded_target_view_dependence.py). Tests: [`test_bounded_target_view_dependence.py`](tests/test_bounded_target_view_dependence.py).



---

# 2. From physical dynamics to operational structure"""
    text = replace_once(text, p78_end, p79_section, "README P79 formal section")

    # P79 becomes Figure 14. Shift every later curated figure by one.
    for number in range(28, 13, -1):
        text = text.replace(f"**Figure {number}.", f"**Figure {number + 1}.")

    text = text.replace(
        "P78 then supplies an exact-rational branch-and-bound lower-bound certificate for the continuous P75 latent family. The remaining challenges are faster and tighter global certification, sharper power, and broader dependent-view alternatives.",
        "P78 then supplies an exact-rational branch-and-bound lower-bound certificate for the continuous P75 latent family. P79 adds robustness to an independently justified bounded amount of target-view dependence. The remaining challenges are independently calibrating or identifying that dependence allowance, sharper robust power, faster global certification, and richer structured dependent-view alternatives.",
    )

    text = text.replace(
        "- develop diagnostics or alternative designs for correlated target-view errors and model misspecification;",
        "- independently calibrate or identify scientifically defensible P79 target-view dependence budgets and develop structured alternatives for correlated target-view errors;",
    )
    text = text.replace(
        "The most immediate target-side problem after P78 is **tighter certified computation and power for full-law adequacy**. P78 supplies a rigorous exact-rational branch-and-bound lower bound for the continuous P75 family, but the nine-dimensional search can be expensive. The next methodological target is stronger certified pruning or relaxation, potentially using interval tightening or polynomial moment-SOS lower bounds, together with sharper power analysis and broader target-view dependence models.",
        "The most immediate target-side problem after P79 is **independent calibration and identification of the dependence allowance, together with sharper robust power**. P79 shows exactly how an externally justified local-dependence budget changes the rejection threshold, but it does not infer that budget from the same bridge data. The next methodological target is to obtain defensible dependence bounds from independent calibration or structured repeated-view designs while also improving P78 global certification efficiency and robust power.",
    )

    p78_falsification = "| Continuous P75 full-law separation is certified | A P78 global lower bound exceeds a valid P77 sampling-radius upper bound | Treating an incomplete parameter search or ordinary floating approximation as a formal certificate |"
    p79_falsification = "| Bounded target-view dependence still permits model compatibility | A P79 certified separation exceeds sampling uncertainty plus an independently justified dependence allowance | Choosing the dependence allowance after seeing the same discrepancy merely to avoid rejection |"
    text = replace_once(text, p78_falsification, p78_falsification + "\n" + p79_falsification, "README P79 falsification")

    p78_prov = "| [P78 equation and provenance record](docs/p78_equation_provenance.md) | Multi-affine box enclosures, global branch-and-bound lower bounds, mesh-gap certification, and P77 handoff provenance |"
    p79_prov = "| [P79 equation and provenance record](docs/p79_equation_provenance.md) | Product-projection dependence defects, observed-law robustness envelopes, and the P77/P78 bounded-dependence rejection gate |"
    text = replace_once(text, p78_prov, p78_prov + "\n" + p79_prov, "README P79 provenance")

    p78_status = "| Continuous-family full-law optimization certificate | **P78 proved for the P75 four-view binary latent family using exact-rational multi-affine box lower bounds and an explicit mesh-gap guarantee** |"
    p79_status = "| Bounded target-view dependence robustness | **P79 proved as a one-sided robustness envelope and rejection theorem under an independently justified dependence allowance** |"
    text = replace_once(text, p78_status, p78_status + "\n" + p79_status, "README P79 status")

    p78_nav = "| Inspect certified continuous P75 model separation | [P78](docs/proposition_78_certified_continuous_model_separation.md) |"
    if p78_nav in text:
        text = replace_once(text, p78_nav, p78_nav + "\n| Inspect bounded target-view dependence robustness | [P79](docs/proposition_79_bounded_target_view_dependence.md) |", "README P79 nav")
    p78_audit = "| Audit P78 continuous-separation equations | [P78 equation and provenance record](docs/p78_equation_provenance.md) |"
    if p78_audit in text:
        text = replace_once(text, p78_audit, p78_audit + "\n| Audit P79 bounded-dependence equations | [P79 equation and provenance record](docs/p79_equation_provenance.md) |", "README P79 audit nav")

    text = text.replace("target-model adequacy, finite-sample adequacy, full-law model-set separation, admissible bridge class", "target-model adequacy, finite-sample adequacy, full-law model-set separation, bounded target-view dependence, admissible bridge class")
    write(path, text)


def patch_citation() -> None:
    path = "CITATION.md"
    text = read(path)
    text = text.replace("0.78.0", "0.79.0")
    text = text.replace("current documented frontier, P78", "current documented frontier, P79")
    text = text.replace("theorem frontier **P78**", "theorem frontier **P79**")
    text = text.replace("P1 through P78 chronological theorem record", "P1 through P79 chronological theorem record")

    p78_cite = "Cite [Proposition 78](docs/proposition_78_certified_continuous_model_separation.md) when relying on the exact multi-affine box enclosure for the P75 model, the certified continuous-family L-infinity lower bound, the mesh-gap convergence guarantee, the exact-rational branch-and-bound implementation, or its strict P77 rejection handoff."
    p79_cite = "Cite [Proposition 79](docs/proposition_79_bounded_target_view_dependence.md) when relying on the product-projection local-dependence defect, the prevalence-weighted robustness envelope around the P75 model family, or the robust rejection rule that adds an independently justified dependence allowance to P77 sampling uncertainty."
    text = replace_once(text, p78_cite, p78_cite + " " + p79_cite, "CITATION P79 proposition")

    p78_scope = "P78 supplies that missing continuous-family lower-bound mechanism for the specific P75 four-view binary latent model. It exploits the model's multi-affine nine-parameter map to compute exact rational cell enclosures on parameter boxes, aggregates those into a global L-infinity lower bound, and proves a mesh-width convergence guarantee. P78 remains a computational certificate under the declared P75 model; it does not turn non-rejection into model validation or identify the latent state with consciousness.\n\n"
    p79_scope = "P79 weakens exact conditional independence among the target views by introducing an explicit local-dependence budget. It compares each latent-state joint view law with the product of its own marginals, transports the prevalence-weighted defect into a neighborhood around the P75 observed-law family, and permits robust rejection only when the certified P78 separation exceeds both P77 sampling uncertainty and an independently justified dependence allowance. The allowance must not be tuned from the same rejection discrepancy merely to avoid rejection, and non-rejection remains inconclusive.\n\n"
    text = replace_once(text, p78_scope, p78_scope + p79_scope, "CITATION P79 scope")

    p78_resource = "- [P78 equation and provenance record](docs/p78_equation_provenance.md): multi-affine box enclosures, exact-rational global lower bounds, mesh-gap convergence, and P77 rejection handoff provenance."
    p79_resource = "- [P79 equation and provenance record](docs/p79_equation_provenance.md): target-view product projection, local-dependence robustness envelope, and P77/P78 rejection-threshold provenance."
    text = replace_once(text, p78_resource, p78_resource + "\n" + p79_resource, "CITATION P79 resource")
    write(path, text)


def patch_roadmap() -> None:
    path = "docs/theorem_roadmap.md"
    text = read(path)
    text = text.replace("current documented theorem frontier is **P78**", "current documented theorem frontier is **P79**")
    text = text.replace("**P1 through P78 with explicit dependency branches**", "**P1 through P79 with explicit dependency branches**")
    text = text.replace("P71-P78", "P71-P79")
    text = text.replace("It does not imply that P78 depends on P70. P78 depends scientifically on P77 and the P75 continuous target-model family, which descend from P19 and the P71-P76 target-side lineage.", "It does not imply that P79 depends on P70. P79 depends scientifically on the P75-P78 target-measurement and full-law adequacy lineage, which descends from P19 and P71-P74.")
    text = replace_once(
        text,
        "&\\text{P78: continuous P75 model distance must be lower-bounded globally and certifiably}\n\\end{aligned}",
        "&\\text{P78: continuous P75 model distance must be lower-bounded globally and certifiably}\\\\\n&\\Downarrow\\\\\n&\\text{P79: bounded residual target-view dependence must be included in the rejection margin}\n\\end{aligned}",
        "roadmap dependency",
    )

    marker = "Direct proof: [P78](proposition_78_certified_continuous_model_separation.md). Provenance: [P78 equation record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](../tests/test_certified_continuous_model_separation.py).\n\n\n## 3. Complete proposition index"
    section = """Direct proof: [P78](proposition_78_certified_continuous_model_separation.md). Provenance: [P78 equation record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py). Tests: [`test_certified_continuous_model_separation.py`](../tests/test_certified_continuous_model_separation.py).

### P79: robust rejection under bounded target-view dependence

Let $R_s$ be the true conditional four-view law under latent target state $s$ and let $\\Pi_s$ be the product of its own one-view marginals. Define

\[
\\delta_s^{(p)}=\\|R_s-\\Pi_s\\|_p,
\\qquad
\\rho_p=(1-\\pi)\\delta_-^{(p)}+\\pi\\delta_+^{(p)}.
\]

The observed law $P=(1-\\pi)R_-+\\pi R_+$ has a P75 counterpart $Q=(1-\\pi)\\Pi_-+\\pi\\Pi_+$, so

\[
\\boxed{d_p(P,\\mathcal M_{4,2})\\le\\rho_p.}
\]

If an independently justified allowance gives $\\rho_p\\le\\bar\\rho_p$, P78 supplies a certified empirical lower bound $L_p$, and P77 supplies a valid sampling-radius upper bound $\\varepsilon_p$, then

\[
\\boxed{L_p>\\varepsilon_p+\\bar\\rho_p
\\Longrightarrow\\text{ reject the bounded-dependence extension}.}
\]

The dependence allowance must be declared or independently calibrated rather than selected post hoc from the same rejection discrepancy. Non-rejection remains inconclusive.

![P79 bounded target-view dependence](figures/p79_bounded_target_view_dependence.svg)

Direct proof: [P79](proposition_79_bounded_target_view_dependence.md). Provenance: [P79 equation record](p79_equation_provenance.md). Implementation: [`bounded_target_view_dependence.py`](../src/consciousness_bridge/bounded_target_view_dependence.py). Tests: [`test_bounded_target_view_dependence.py`](../tests/test_bounded_target_view_dependence.py).


## 3. Complete proposition index"""
    text = replace_once(text, marker, section, "roadmap P79 section")

    lines = text.splitlines()
    p78_index = next((i for i, line in enumerate(lines) if line.startswith("| [P78](")), None)
    if p78_index is None:
        raise RuntimeError("roadmap P78 index row missing")
    if not any(line.startswith("| [P79](") for line in lines):
        lines.insert(p78_index + 1, "| [P79](proposition_79_bounded_target_view_dependence.md) | bounded-dependence robustness envelope | robust target-model rejection under independently justified local-dependence allowance | proved conditional theorem |")
    text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    write(path, text)


def patch_navigation() -> None:
    path = "docs/research_navigation.md"
    text = read(path)
    text = text.replace("current documented theorem frontier is **P78**", "current documented theorem frontier is **P79**")
    text = text.replace("**P1 through P78**", "**P1 through P79**")
    text = text.replace("from P1 through P78", "from P1 through P79")
    text = text.replace("P71-P78", "P71-P79")

    p78_item = "[P78 certified continuous P75 model separation](proposition_78_certified_continuous_model_separation.md)"
    idx = text.find(p78_item)
    if idx < 0:
        raise RuntimeError("navigation P78 reading item missing")
    line_end = text.find("\n", idx)
    if "P79 bounded target-view dependence" not in text:
        text = text[: line_end + 1] + "13. [P79 bounded target-view dependence](proposition_79_bounded_target_view_dependence.md) for robust P77/P78 rejection after an independently justified residual-dependence allowance is added to sampling uncertainty.\n" + text[line_end + 1 :]

    p78_branch = "| Certified continuous model separation | P78 | Supplies an exact-rational global lower bound for the continuous P75 model family and closes the P77 optimization-direction gap | [P78](proposition_78_certified_continuous_model_separation.md) |"
    if p78_branch in text:
        text = replace_once(text, p78_branch, p78_branch + "\n| Bounded target-view dependence robustness | P79 | Enlarges the P75 family by an independently justified local-dependence allowance and preserves rejection beyond sampling plus dependence margins | [P79](proposition_79_bounded_target_view_dependence.md) |", "navigation P79 branch")

    lines = text.splitlines()
    p78_index = next((i for i, line in enumerate(lines) if line.startswith("| P78 |")), None)
    if p78_index is None:
        raise RuntimeError("navigation P78 index row missing")
    if not any(line.startswith("| P79 |") for line in lines):
        lines.insert(p78_index + 1, "| P79 | [Bounded target-view dependence robustness](proposition_79_bounded_target_view_dependence.md) | robust model rejection with independently justified local-dependence budget |")
    text = "\n".join(lines) + ("\n" if text.endswith("\n") else "")
    write(path, text)


def patch_detail() -> None:
    path = "docs/detailed_proposition_record.md"
    text = read(path)
    text = text.replace("## Complete P1 to P78 chronology", "## Complete P1 to P79 chronology")
    marker = "Direct P78 proof: [certified continuous model separation](proposition_78_certified_continuous_model_separation.md). Equation classification: [P78 equation and provenance record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py).\n\n\n---\n\n## Scientific interpretation of the chronology"
    section = """Direct P78 proof: [certified continuous model separation](proposition_78_certified_continuous_model_separation.md). Equation classification: [P78 equation and provenance record](p78_equation_provenance.md). Implementation: [`certified_continuous_model_separation.py`](../src/consciousness_bridge/certified_continuous_model_separation.py).

**P79** weakens the exact conditional-independence assumption in the P75 target-view model by introducing an explicit residual-dependence budget. For each latent state, the true conditional four-view law is compared with the product of its own one-view marginals. The prevalence-weighted discrepancy bounds how far the observed population law can move away from the P75 conditionally independent model family.

If a scientifically independent protocol supplies a dependence allowance $\\bar\\rho_p$, P78 supplies a certified empirical model-distance lower bound $L_p$, and P77 supplies sampling uncertainty $\\varepsilon_p$, then $L_p>\\varepsilon_p+\\bar\\rho_p$ rejects every population law satisfying that bounded-dependence allowance. The allowance cannot be chosen after observing the same discrepancy merely to avoid rejection, and failure to reject remains inconclusive.

Direct P79 proof: [bounded target-view dependence robustness](proposition_79_bounded_target_view_dependence.md). Equation classification: [P79 equation and provenance record](p79_equation_provenance.md). Implementation: [`bounded_target_view_dependence.py`](../src/consciousness_bridge/bounded_target_view_dependence.py).


---

## Scientific interpretation of the chronology"""
    text = replace_once(text, marker, section, "detail P79 chronology")
    text = text.replace("P71-P78 return to the target side", "P71-P79 return to the target side")
    text = text.replace(
        "P78 supplies the missing global lower-bound certificate for the continuous P75 latent family using exact-rational multi-affine box refinement. The next problems are computational efficiency, sharper power, and robust alternatives for residually dependent or learned target-view systems.",
        "P78 supplies the missing global lower-bound certificate for the continuous P75 latent family using exact-rational multi-affine box refinement. P79 then makes rejection robust to an independently justified bounded amount of residual target-view dependence. The next problems are independent calibration or identification of that dependence budget, computational efficiency, sharper robust power, and richer structured dependent-view or learned target-view systems.",
    )
    write(path, text)


def patch_equation_map() -> None:
    path = "docs/equation_and_citation_map.md"
    text = read(path)
    if "# P79 bounded target-view dependence robustness" not in text:
        text = text.rstrip() + """

# P79 bounded target-view dependence robustness

P79 weakens exact conditional independence of the P75 target views by introducing an explicit, independently justified local-dependence allowance.

- **Product projection:**
  \[
  \\Pi_s(x)=\\prod_{j=1}^4R_{s,j}(x_j).
  \]
  **Status:** standard product construction from fixed marginals.

- **Conditional dependence defect:**
  \[
  \\delta_s^{(p)}=\\|R_s-\\Pi_s\\|_p.
  \]
  **Status:** standard norm discrepancy.

- **Observed-law robustness envelope:**
  \[
  \\rho_p=(1-\\pi)\\delta_-^{(p)}+\\pi\\delta_+^{(p)},
  \\qquad
  d_p(P,\\mathcal M_{4,2})\\le\\rho_p.
  \]
  **Status:** standard triangle inequality and mixture convexity assembled for the P75 target-view model.

- **Robust rejection gate:**
  \[
  L_p>\\varepsilon_p+\\bar\\rho_p
  \Longrightarrow
  \\text{reject the bounded-dependence extension}.
  \]
  **Status:** standard distance-to-set transport combined with the repository's P77/P78 certification chain and an independently justified P79 dependence allowance.

The allowance must not be chosen post hoc from the same rejection discrepancy. Non-rejection remains inconclusive.

Proof: [P79](proposition_79_bounded_target_view_dependence.md). Dedicated provenance: [P79 equation and provenance record](p79_equation_provenance.md). Implementation: [`bounded_target_view_dependence.py`](../src/consciousness_bridge/bounded_target_view_dependence.py). Tests: [`test_bounded_target_view_dependence.py`](../tests/test_bounded_target_view_dependence.py).

The physical-to-experiential bridge remains open.
"""
    write(path, text)


def patch_changelog() -> None:
    path = "CHANGELOG.md"
    text = read(path)
    if not text.startswith("# 0.79.0 - 2026-09-10"):
        entry = """# 0.79.0 - 2026-09-10

## Proposition 79: robust rejection under bounded target-view dependence

- adds a quantitative local-dependence defect comparing each latent-state joint target-view law with the product of its own marginals;
- proves a prevalence-weighted observed-law neighborhood bound around the P75 conditionally independent model family;
- adds the robust P77/P78 rejection rule requiring certified separation beyond both sampling uncertainty and an independently justified dependence allowance;
- explicitly forbids tuning the dependence allowance from the same discrepancy merely to avoid rejection;
- keeps non-rejection inconclusive and does not promote bounded local dependence into a latent ontology;
- adds the P79 proof, provenance record, implementation, tests, theorem figure, and public research integration;
- keeps the physical-to-experiential bridge open.

"""
        write(path, entry + text)


def patch_website() -> None:
    path = "website/index.html"
    text = read(path)
    text = text.replace("v0.78.0", "v0.79.0")
    text = text.replace("<strong>78</strong><span>proposition-level results</span>", "<strong>79</strong><span>proposition-level results</span>")
    text = text.replace("all 78 results", "all 79 results")
    text = text.replace("P71-P78", "P71-P79")
    text = text.replace("P1-P78", "P1-P79")
    if "p79_bounded_target_view_dependence.svg" not in text:
        marker = "</main>"
        block = """
    <section class="figure-card">
      <img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p79_bounded_target_view_dependence.svg" alt="P79 bounded target-view dependence robustness" />
      <div>
        <p class="eyebrow">P79</p>
        <h2>Robust rejection under bounded target-view dependence</h2>
        <p>P79 replaces exact conditional independence by an independently justified dependence allowance. P77/P78 rejection survives only when certified model separation exceeds both sampling uncertainty and that allowance. The allowance cannot be tuned post hoc merely to avoid rejection.</p>
        <a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_79_bounded_target_view_dependence.md">Read Proposition 79</a>
      </div>
    </section>

"""
        text = replace_once(text, marker, block + marker, "website P79 block")
    write(path, text)

    path = "website/research-map.html"
    text = read(path)
    text = text.replace("P71-P78", "P71-P79")
    text = text.replace("P1-P78", "P1-P79")
    text = text.replace("P1 through P78", "P1 through P79")
    text = text.replace("78 results", "79 results")
    if "P79: Bounded target-view dependence robustness" not in text:
        marker = "</main>"
        block = """
    <section class="boundary">
      <h2>P79: Bounded target-view dependence robustness</h2>
      <p>P79 weakens exact conditional independence of the repeated target views. An independently justified residual-dependence budget enlarges the P75 model by a controlled neighborhood.</p>
      <p>Robust rejection requires the P78 certified separation to exceed the sum of P77 sampling uncertainty and the P79 dependence allowance. The allowance must not be selected from the same discrepancy merely to rescue the model.</p>
      <p><a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_79_bounded_target_view_dependence.md">Read Proposition 79</a></p>
      <img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p79_bounded_target_view_dependence.svg" alt="P79 bounded target-view dependence robustness" />
    </section>

"""
        text = replace_once(text, marker, block + marker, "research map P79 block")
    write(path, text)

    path = "website/visual-atlas.html"
    text = read(path)
    if "p79_bounded_target_view_dependence.svg" not in text:
        marker = "</main>"
        block = """
    <section class="figure-card">
      <img src="https://raw.githubusercontent.com/MahsaKeikha/mathematical-consciousness-bridge/main/docs/figures/p79_bounded_target_view_dependence.svg" alt="P79 bounded target-view dependence robustness" />
      <div>
        <p class="eyebrow">P79</p>
        <h2>Bounded Target-View Dependence Robustness</h2>
        <p>The figure shows how latent-state local dependence is converted into a robustness allowance around the P75 family and then combined with P77 sampling uncertainty and P78 certified model separation.</p>
        <a href="https://github.com/MahsaKeikha/mathematical-consciousness-bridge/blob/main/docs/proposition_79_bounded_target_view_dependence.md">Open the P79 proof</a>
      </div>
    </section>

"""
        text = replace_once(text, marker, block + marker, "visual atlas P79 block")
    write(path, text)


def main() -> None:
    patch_readme()
    patch_citation()
    patch_roadmap()
    patch_navigation()
    patch_detail()
    patch_equation_map()
    patch_changelog()
    patch_website()
    print("P79 publication patch: PASS")


if __name__ == "__main__":
    main()
